name: eco_system_things
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
    sdk: ^3.8.1

dependencies:
    flutter_launcher_icons: ^0.14.4
    hive_flutter: ^1.1.0
    hive: ^2.2.3
    image: ^4.5.4
    path_provider: ^2.1.5
    firebase_database: ^12.0.0
    firebase_core: ^4.0.0
    url_launcher: ^6.3.2
    geolocator: ^14.0.2
    image_picker: ^1.1.2
    http: ^1.4.0
    flutter:
        sdk: flutter

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^5.0.0

flutter:
    uses-material-design: true
    assets:
        - assets/images/logo.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png" 