// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEVmAnEkTHkTHzz7soNf1Q_qcFHBlZcbs',
    appId: '1:1000392374400:web:91f1c0068d38def85cce65',
    messagingSenderId: '1000392374400',
    projectId: 'ecosys-133d0',
    authDomain: 'ecosys-133d0.firebaseapp.com',
    storageBucket: 'ecosys-133d0.firebasestorage.app',
    measurementId: 'G-YN73ZWTDFX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpXuS26JbN7TDx5auMGtpkFCp21kWB50Q',
    appId: '1:1000392374400:android:d7f60a62888048a95cce65',
    messagingSenderId: '1000392374400',
    projectId: 'ecosys-133d0',
    storageBucket: 'ecosys-133d0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnUTwDf1l3tfk4-EQ3EEHOH4fU6XGE1qE',
    appId: '1:1000392374400:ios:ef5f211a99d7c7d65cce65',
    messagingSenderId: '1000392374400',
    projectId: 'ecosys-133d0',
    storageBucket: 'ecosys-133d0.firebasestorage.app',
    iosBundleId: 'com.example.ecoSystemThings',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnUTwDf1l3tfk4-EQ3EEHOH4fU6XGE1qE',
    appId: '1:1000392374400:ios:ef5f211a99d7c7d65cce65',
    messagingSenderId: '1000392374400',
    projectId: 'ecosys-133d0',
    storageBucket: 'ecosys-133d0.firebasestorage.app',
    iosBundleId: 'com.example.ecoSystemThings',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEVmAnEkTHkTHzz7soNf1Q_qcFHBlZcbs',
    appId: '1:1000392374400:web:f72fdee1dd4831ba5cce65',
    messagingSenderId: '1000392374400',
    projectId: 'ecosys-133d0',
    authDomain: 'ecosys-133d0.firebaseapp.com',
    storageBucket: 'ecosys-133d0.firebasestorage.app',
    measurementId: 'G-4QKXEKV8H3',
  );
}